image: registry.gitlab.com/yakshaving.art/dockerfiles/go-builder:0.0.1
stages:
  - build
  - image
  - release

variables:
  CGO_ENABLED: 0

cache:
  paths:
  - vendor

test:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - go mod vendor
  - make test

build:
  stage: build
  artifacts:
    paths:
    - chief-alert-executor-*
  script:
  - make build
  - GOARCH=arm64 make build
  - GOARCH=arm GOARM=6 make build

.docker: &docker
  image: docker:stable
  services:
  - docker:dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  after_script:
    - docker logout

.build_image: &build_image
  <<: *docker
  stage: image
  script:
    - echo Building ${ARCH} image
    - cp Dockerfile.${ARCH} Dockerfile
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${ARCH}-latest .
    - docker push ${CI_REGISTRY_IMAGE}:${ARCH}-latest
    - rm Dockerfile

build_arm64:
  <<: *build_image
  variables:
    ARCH: arm64

build_amd64:
  <<: *build_image
  variables:
    ARCH: amd64

build_armhf:
  <<: *build_image
  variables:
    ARCH: armhf

release_latest:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:latest
        ${CI_REGISTRY_IMAGE}:amd64-latest
        ${CI_REGISTRY_IMAGE}:arm64-latest
        ${CI_REGISTRY_IMAGE}:armhf-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE}
        ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest annotate ${CI_REGISTRY_IMAGE}
        ${CI_REGISTRY_IMAGE}:armhf-latest --os linux --arch arm --variant 6
    - docker manifest push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master

release_tag:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:amd64-latest
        ${CI_REGISTRY_IMAGE}:arm64-latest
        ${CI_REGISTRY_IMAGE}:armhf-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest annotate ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:armhf-latest --os linux --arch arm --variant 6
    - docker manifest push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags
