---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chief-alert-executor
data:
  config.yml: |-
    ---
    matchers:
      - name: Dummy
        labels:
          alertname: .*
        annotations: {}
        command: echo
        args:
        - Dummy alert triggered